---
title: "R Notebook"
output: html_notebook
---

```{r}
# read heart data
heart_data <- read.csv("../data/heart_attack_data.csv", header=TRUE)
```

```{r}
head(heart_data)
```
```{r}
dim(heart_data)
```

```{r}
str(heart_data)
```
```{r}
heart_data$sex <- factor(heart_data$sex)
heart_data$cp <- factor(heart_data$cp)
heart_data$fbs <- factor(heart_data$fbs)
heart_data$restecg <- factor(heart_data$restecg)
heart_data$exang <- factor(heart_data$exang)
heart_data$target <- factor(heart_data$target)

```

```{r}
str(heart_data)
```
```{r}
library(tidyverse)
```

```{r}
heart_data %>%
  ggplot(aes(x = trestbps, y = chol)) +
  geom_point(na.rm = TRUE)
```
```{r}
heart_data %>%
  ggplot(aes(x = trestbps, y = chol)) +
  geom_line(na.rm = TRUE)
```
```{r}
heart_data %>%
  ggplot(aes(x = age)) +
  geom_histogram(na.rm = TRUE)
```
```{r}
gender_dist <- heart_data %>%
  count(sex)

gender_dist
```

```{r}
gender_dist %>%
  ggplot(aes(x=sex, y=n)) +
  geom_bar(stat ="identity") +
  ggtitle("Distribution of Gender")
```




```{r}
heart_data %>%
  ggplot(aes(x = sex)) +
  geom_bar(na.rm = TRUE)
```

```{r}
# plot the scatter plot showing the relationship between age and chol

heart_data %>%
  ggplot(aes (x = age, y = chol)) +
   geom_point(aes(color = sex), na.rm = TRUE) +
   ggtitle ("Age vs Cholesterol by Gender")
```

```{r}
heart_data %>%
  ggplot(aes(x = target)) +
  geom_bar(color = "black", fill = "blue") +
  xlab("Gender")
   ylab("hello")
```

```{r}
heart_data %>%
  ggplot(aes(x = cp)) +
  geom_bar(na.rm = TRUE)
```
```{r}
cp_dist <- heart_data %>%
  count(cp)

cp_dist %>%
  ggplot(aes(x=reorder(cp, n), y=n)) +
  geom_bar(stat = "identity", color = "black", fill = "pink") +
  xlab('Chest Pain') +
    ylab('Frequency') +
    ggtitle("Distribution of chest pain type")
```

